spring:
    datasource:
        url: jdbc:mysql://localhost/mlyauth?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: MYSQL
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
