spring:
    datasource:
        url: jdbc:mysql://idp-database:3306/idp?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: MYSQL
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    liquibase:
      contexts: uat

keystore:
  path: classpath:keys/keystore.jks
  alias: sgi.prima-solutions.com
  password: Bourso$17