databaseChangeLog:
  - changeSet:
      id: 1
      author: mlyahmed
      changes:
        - createTable:
            tableName: APPLICATION
            columns:
              - column:
                  name: ID
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: APP_NAME
                  type: varchar(100)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: TITLE
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: AUTHENTICATION_INFO_ID
                  type: bigint
                  constraints:
                      nullable: true
                      unique: true
  - changeSet:
      id: 2
      author: mlyahmed
      changes:
        - addForeignKeyConstraint:
            baseTableName: APPLICATION
            baseColumnNames: AUTHENTICATION_INFO_ID
            referencedTableName: AUTHENTICATION_INFO
            referencedColumnNames: ID
            constraintName: application_auth_fk_auth_id