--liquibase formatted SQL
--changeset mlyahmed:1 runOnChange:FALSE
DELETE FROM APPLICATION_ASPECT;
DELETE FROM PERSON_APPLICATION;
DELETE FROM APPLICATION;
INSERT INTO APPLICATION (ID, APP_NAME, AUTH_ASPECT, TITLE) VALUES (9000, 'PolicyDev', 'SP_SAML', 'Policy Dev');